packages:
  - "*"

catalog:
  "@clusterio/lib": ^2.0.0-alpha.21
  "@clusterio/web_ui": ^2.0.0-alpha.21
  "@sinclair/typebox": ^0.30.4
  "@types/node": ^20.14.9
  "@types/react": ^18.2.21
  "typescript": ^5.5.3
  "antd": ^5.13.0
  "react": ^18.2.0
  "react-dom": ^18.2.0
  "webpack": ^5.98.0
  "webpack-cli": ^5.1.4
  "webpack-merge": ^5.9.0
