packages:
  - '*'

catalog:
  '@clusterio/lib': 2.0.0-alpha.22b
  '@clusterio/web_ui': 2.0.0-alpha.22b
  '@sinclair/typebox': ^0.30.4
  '@types/node': ^20.19.29
  '@types/react': 18.2.0
  antd: 5.24.2
  react: 18.2.0
  react-dom: 18.2.0
  typescript: ^5.9.3
  webpack: 5.98.0
  webpack-cli: 5.1.4
  webpack-merge: 5.9.0
